# Site-wide settings
# ------------------

title: dolin\\it

author:
  name: Blake Dolin
  email: blake@dolinit.com

# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: personal blog and homepage.

minima:
  social_links:
    - title: linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/blakedolin/"
    - title: discord
      icon: discord
      url: "https://discord.com/users/231844849433706506"