# Site-wide settings
# ------------------

title: dolinit.com

author:
  name: Blake Dolin
  email: blake@dolinit.com

# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: dolin\\IT
